'use client';
import { useEffect, useState } from 'react';
import type { Session, SupabaseClient, User } from '@supabase/supabase-js';
import { Layers3, Loader2 } from 'lucide-react';
import { getSupabase } from '@/lib/supabase/client';
import { errorMessage } from '@/lib/timesheets/use-workspace';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
export function AuthGate({children}:{children:(db:SupabaseClient,user:User)=>React.ReactNode}){
 const [db]=useState(getSupabase);const [session,setSession]=useState<Session|null>(null);const [checking,setChecking]=useState(true);const [mode,setMode]=useState<'signin'|'signup'|'reset'|'recovery'>('signin');
 const [email,setEmail]=useState('');const [password,setPassword]=useState('');const [busy,setBusy]=useState(false);const [message,setMessage]=useState('');const [error,setError]=useState('');
 useEffect(()=>{if(!db)return;let active=true;db.auth.getSession().then(({data,error})=>{if(!active)return;if(error)setError(error.message);setSession(data.session);setChecking(false);});const {data}=db.auth.onAuthStateChange((event,s)=>{if(!active)return;setSession(s);setChecking(false);if(event==='PASSWORD_RECOVERY')setMode('recovery');});return()=>{active=false;data.subscription.unsubscribe();};},[db]);
 async function submit(event:React.FormEvent){event.preventDefault();if(!db||busy)return;setBusy(true);setError('');setMessage('');try{if(mode==='signin'){const {error}=await db.auth.signInWithPassword({email,password});if(error)throw error;}else if(mode==='signup'){const {data,error}=await db.auth.signUp({email,password,options:{emailRedirectTo:window.location.origin}});if(error)throw error;if(!data.session)setMessage('Check your email to confirm your account, then sign in.');}else if(mode==='reset'){const {error}=await db.auth.resetPasswordForEmail(email,{redirectTo:window.location.origin});if(error)throw error;setMessage('If this email has an account, a password reset link has been sent.');}else{const {error}=await db.auth.updateUser({password});if(error)throw error;setMode('signin');setPassword('');setMessage('Password updated.');}}catch(e){setError(errorMessage(e));}finally{setBusy(false);}}
 if(db&&checking)return <div className="auth-shell"><Loader2 className="animate-spin"/><p>Opening your workspace…</p></div>;
 if(db&&session&&mode!=='recovery')return <>{children(db,session.user)}</>;
 return <div className="auth-shell"><div className="auth-card"><div className="brand"><span className="brand-mark"><Layers3/></span>ChronoTide</div><h1>{!db?'Connect your workspace':mode==='signup'?'Your work, in one place.':mode==='reset'?'Reset your password':mode==='recovery'?'Choose a new password':'Welcome back.'}</h1><p>{!db?'Set your Supabase URL and publishable key in .env.local, then restart the app.':'Private timesheets, saved securely across your devices.'}</p>{db&&<form onSubmit={submit}>{mode!=='recovery'&&<div><Label htmlFor="auth-email">Email</Label><Input id="auth-email" type="email" autoComplete="email" required value={email} onChange={e=>setEmail(e.target.value)}/></div>}{mode!=='reset'&&<div><Label htmlFor="auth-password">Password</Label><Input id="auth-password" type="password" autoComplete={mode==='signin'?'current-password':'new-password'} minLength={mode==='signin'?undefined:8} required value={password} onChange={e=>setPassword(e.target.value)}/></div>}{error&&<p role="alert" className="form-error">{error}</p>}{message&&<p role="status">{message}</p>}<Button type="submit" disabled={busy}>{busy?<Loader2 className="animate-spin"/>:null}{mode==='signin'?'Sign in':mode==='signup'?'Create account':mode==='reset'?'Send reset link':'Update password'}</Button><div className="auth-links">{mode==='signin'?<><Button type="button" variant="link" onClick={()=>{setMode('signup');setError('');}}>Create an account</Button><Button type="button" variant="link" onClick={()=>{setMode('reset');setError('');}}>Forgot password?</Button></>:<Button type="button" variant="link" onClick={()=>{setMode('signin');setError('');}}>Back to sign in</Button>}</div></form>}</div></div>;
}
