'use client';
import { useState } from 'react';
import { Pencil, Plus, Archive, Loader2 } from 'lucide-react';
import { toast } from 'sonner';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogDescription } from '@/components/ui/dialog';
import { Select, SelectTrigger, SelectContent, SelectValue, SelectItem } from '@/components/ui/select';
import { type Client, type LiveProject, type Profile } from '@/lib/timesheets/models';
import { type Entry, formatDuration, total } from '@/lib/timesheets/domain';
import { errorMessage } from '@/lib/timesheets/use-workspace';
export function Management({kind,clients,projects,entries,saveClient,saveProject}:{kind:'Clients'|'Projects';clients:Client[];projects:LiveProject[];entries:Entry[];saveClient:(id:string,name:string,archived:string|null)=>Promise<void>;saveProject:(id:string,name:string,client:string,color:string,archived:string|null)=>Promise<void>}) {
 const [form,setForm]=useState<{id:string;name:string;clientId:string;color:string;archivedAt:string|null;exists:boolean}|null>(null);const [busy,setBusy]=useState(false);const [error,setError]=useState('');
 const items=kind==='Clients'?clients:projects;
 function open(item?:Client|LiveProject){setError('');setForm({id:item?.id||crypto.randomUUID(),name:item?.name||'',clientId:item&&'clientId'in item?item.clientId:clients.find(c=>!c.archivedAt)?.id||'',color:item&&'color'in item?item.color:'#6864e8',archivedAt:item?.archivedAt||null,exists:!!item});}
 async function save(){if(!form||busy)return;setBusy(true);setError('');try{if(!form.name.trim())throw new Error('Enter a name.');if(kind==='Clients')await saveClient(form.id,form.name.trim(),form.archivedAt);else{if(!form.clientId)throw new Error('Create a client first.');await saveProject(form.id,form.name.trim(),form.clientId,form.color,form.archivedAt);}setForm(null);toast.success('Saved online');}catch(e){setError(errorMessage(e));}finally{setBusy(false);}}
 return <><div className="management-actions"><Button onClick={()=>open()}><Plus/>New {kind==='Clients'?'client':'project'}</Button></div><section className="management-grid">{items.length===0?<div className="empty-state"><h2>{kind==='Projects'?'Create your first project':'Add a client'}</h2><p>{kind==='Projects'?'Give your work a home before entering hours.':'Clients keep your projects and monthly reports organized.'}</p><Button onClick={()=>open()}><Plus/>Create {kind==='Projects'?'project':'client'}</Button></div>:items.map(item=><article key={item.id} className="project-card"><div className="project-card-top"><span className="project-avatar" style={{color:'color'in item?String(item.color):undefined}}>{item.name.slice(0,2).toUpperCase()}</span><span className="status-pill">{item.archivedAt?'Archived':'Active'}</span></div><h2>{item.name}</h2>{'clientId'in item&&<p>{clients.find(c=>c.id===item.clientId)?.name}</p>}<div className="project-card-hours"><strong>{formatDuration(total(entries.filter(e=>kind==='Clients'?projects.find(p=>p.id===e.project)?.clientId===item.id:e.project===item.id)))}</strong><span>logged hours</span></div><Button variant="outline" onClick={()=>open(item)}><Pencil/>Edit {kind==='Clients'?'client':'project'}</Button></article>)}</section><Dialog open={!!form} onOpenChange={open=>{if(!open&&!busy)setForm(null);}}><DialogContent><DialogHeader><DialogTitle>{form?.exists?'Edit':'New'} {kind==='Clients'?'client':'project'}</DialogTitle><DialogDescription>Archiving keeps historical time entries and reports intact.</DialogDescription></DialogHeader>{form&&<form className="management-form" onSubmit={e=>{e.preventDefault();void save();}}><div><Label htmlFor="entity-name">Name</Label><Input id="entity-name" maxLength={200} required value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></div>{kind==='Projects'&&<div><Label>Client</Label><Select disabled={form.exists} value={form.clientId} onValueChange={clientId=>setForm({...form,clientId})}><SelectTrigger aria-label="Project client"><SelectValue placeholder="Choose client"/></SelectTrigger><SelectContent>{clients.filter(c=>!c.archivedAt||c.id===form.clientId).map(c=><SelectItem key={c.id} value={c.id}>{c.name}</SelectItem>)}</SelectContent></Select></div>}{error&&<p role="alert" className="form-error">{error}</p>}<div className="entry-actions">{form.exists&&<Button type="button" variant="outline" onClick={()=>setForm({...form,archivedAt:form.archivedAt?null:new Date().toISOString()})}><Archive/>{form.archivedAt?'Restore':'Archive'}</Button>}<span className="input-help">{form.archivedAt?'Will be archived':''}</span><Button type="submit" disabled={busy}>{busy&&<Loader2 className="animate-spin"/>}Save</Button></div></form>}</DialogContent></Dialog></>;
}
export function Preferences({profile,clients,save,signOut,dirty}:{profile:Profile;clients:Client[];save:(values:Pick<Profile,'reporting_name'|'timezone'|'preferred_client_id'>)=>Promise<void>;signOut:()=>Promise<void>;dirty:boolean}){
 const [name,setName]=useState(profile.reporting_name);const [timezone,setTimezone]=useState(profile.timezone);const [preferred,setPreferred]=useState(profile.preferred_client_id||'none');const [busy,setBusy]=useState(false);const [error,setError]=useState('');
 async function submit(e:React.FormEvent){e.preventDefault();setBusy(true);setError('');try{await save({reporting_name:name.trim(),timezone,preferred_client_id:preferred==='none'?null:preferred});toast.success('Preferences saved online');}catch(e){setError(errorMessage(e));}finally{setBusy(false);}}
 return <section className="settings-stack"><form onSubmit={submit} className="settings-card management-form"><h2>Personal preferences</h2><div><Label htmlFor="report-name">Your name on reports</Label><Input id="report-name" value={name} onChange={e=>setName(e.target.value)} placeholder="Your full name"/></div><div><Label htmlFor="timezone">Timezone</Label><Input id="timezone" value={timezone} onChange={e=>setTimezone(e.target.value)}/><p className="input-help">Used for today and current periods. Work dates never shift between timezones.</p></div><div><Label>Default client</Label><Select value={preferred} onValueChange={setPreferred}><SelectTrigger aria-label="Default client"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="none">Automatic</SelectItem>{clients.filter(c=>!c.archivedAt||c.id===preferred).map(c=><SelectItem key={c.id} value={c.id}>{c.name}{c.archivedAt?' (archived)':''}</SelectItem>)}</SelectContent></Select></div>{error&&<p role="alert" className="form-error">{error}</p>}<Button disabled={busy} type="submit">{busy&&<Loader2 className="animate-spin"/>}Save preferences</Button></form><div className="settings-card"><h2>Connected to Supabase</h2><p>Your account’s records are private and available on any device after signing in.</p><Button variant="outline" disabled={dirty} onClick={()=>void signOut()}>Sign out</Button>{dirty&&<p className="input-help">Save or discard your time-entry changes before signing out.</p>}</div></section>;
}
